apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: smb-test-container
    securityContext:
      privileged: true
    volumeMounts:
    - name: samba-mount
      mountPath: /mnt/smb0:shared
  volumes:
  - name: samba-mount
    hostPath:
      path: /mnt/smb0
