apiVersion: v1
kind: Secret
metadata:
  name: smb-config
data:
  # Base64 encoded values
  SMB_SERVER: 'IPSERVER'
  SMB_SHARE: 'sharedFolder'
  SMB_USER: 'user'
  SMB_PASSWORD: 'password'
  SMB_MOUNT_PATH: '/mnt/smb0'